version: '3.8'

services:

  dnsmasq:
    build:
      context: docker/dnsmasq
    ports:
      - "40000:53/udp"
    networks:
      - wireguard_network
    env_file:
      - ../../.env

  orchestration:
    build:
      context: docker/orchestration
    ports:
      - "40001:8080/udp"
    networks:
      - wireguard_network
    env_file:
      - ../../.env

  wireguard:
    build:
      context: docker/wireguard
    ports:
      - "40002:51820/udp"
    depends_on:
      - dnsmasq
    networks:
      - wireguard_network
    env_file:
      - ../../.env

networks:
  wireguard_network:
    driver: bridge
