version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend/react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

  backend:
    build:
      context: ./src/backend/spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  db:
    build:
      context: ./src/backend/database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backup:/docker-entrypoint-initdb.d
      - ./backups:/backups
    entrypoint: ["sh", "/docker-entrypoint-initdb.d/entrypoint.sh"]
    stop_grace_period: 2m
    stop_signal: SIGTERM

volumes:
  db-data:
  backups:
