apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: microservices
type: Opaque
data:
  postgres_user: <base64-encoded-user>
  postgres_password: <base64-encoded-password>
  postgres_db: <base64-encoded-db-name>
