CREATE TABLE daily_forecast_data (
     id UUID PRIMARY KEY,
     clouds DOUBLE PRECISION,
     dt INTEGER,
     feel_day DOUBLE PRECISION,
     feel_eve DOUBLE PRECISION,
     feel_morn DOUBLE PRECISION,
     feel_night DOUBLE PRECISION,
     humidity DOUBLE PRECISION,
     pressure DOUBLE PRECISION,
     rain DOUBLE PRECISION,
     snow DOUBLE PRECISION,
     sunrise INTEGER,
     sunset INTEGER,
     temp_day DOUBLE PRECISION,
     temp_eve DOUBLE PRECISION,
     temp_max DOUBLE PRECISION,
     temp_min DOUBLE PRECISION,
     temp_morn DOUBLE PRECISION,
     temp_night DOUBLE PRECISION,
     weather_description VARCHAR(255),
     weather_icon VARCHAR(255),
     weather_id INTEGER,
     weather_main VARCHAR(255),
     deg DOUBLE PRECISION,
     speed DOUBLE PRECISION
);

CREATE TABLE daily_weather_data_30_day (
    id UUID PRIMARY KEY,
    timezone INTEGER,
    cnt INTEGER,
    code VARCHAR(255),
    message DOUBLE PRECISION
);

CREATE TABLE hourly_forecast_data (
    id UUID PRIMARY KEY,
    clouds_all INTEGER,
    dt INTEGER,
    dt_txt VARCHAR(255),
    feels_like DOUBLE PRECISION,
    grnd_level DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    pressure DOUBLE PRECISION,
    sea_level DOUBLE PRECISION,
    temp DOUBLE PRECISION,
    temp_kf DOUBLE PRECISION,
    temp_max DOUBLE PRECISION,
    temp_min DOUBLE PRECISION,
    pop DOUBLE PRECISION,
    rain_1h DOUBLE PRECISION,
    snow_1h DOUBLE PRECISION,
    sys_pod VARCHAR(255),
    visibility INTEGER,
    weather_description VARCHAR(255),
    weather_icon VARCHAR(255),
    weather_id INTEGER,
    weather_main VARCHAR(255),
    wind_deg DOUBLE PRECISION,
    wind_gust DOUBLE PRECISION,
    wind_speed DOUBLE PRECISION
);

CREATE TABLE hourly_weather_data_4_day (
    id UUID PRIMARY KEY,
    sunrise INTEGER,
    sunset INTEGER,
    timezone INTEGER,
    cnt INTEGER,
    cod INTEGER,
    fetch_time TIMESTAMP,
    message INTEGER
);

CREATE TABLE current_weather_data (
    id UUID PRIMARY KEY ,
    all_clouds INTEGER,
    cod INTEGER,
    dt INTEGER,
    fetch_time TIMESTAMP,
    feels_like DOUBLE PRECISION,
    humidity DOUBLE PRECISION,
    pressure DOUBLE PRECISION,
    temperature DOUBLE PRECISION,
    temp_max DOUBLE PRECISION,
    temp_min DOUBLE PRECISION,
    rain_1h DOUBLE PRECISION,
    rain_3h DOUBLE PRECISION,
    snow_1h DOUBLE PRECISION,
    snow_3h DOUBLE PRECISION,
    sunrise INTEGER,
    sunset INTEGER,
    timezone INTEGER,
    visibility INTEGER,
    weather_description VARCHAR(255),
    weather_icon VARCHAR(255),
    weather_id INTEGER,
    weather_main VARCHAR(255),
    wind_deg DOUBLE PRECISION,
    wind_gust DOUBLE PRECISION,
    wind_speed DOUBLE PRECISION
);

CREATE TABLE events (
    id UUID PRIMARY KEY,
    name VARCHAR(512),
    address VARCHAR(1000),
    city VARCHAR(255),
    state VARCHAR(255),
    zip_code VARCHAR(255),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    category VARCHAR(255),
    description VARCHAR(2000),
    event_site_url VARCHAR(1000),
    image_url VARCHAR(1000),
    is_free BOOLEAN,
    time_start VARCHAR(255),
    time_end VARCHAR(255),
    attending_count INTEGER,
    interested_count INTEGER,
    is_canceled BOOLEAN,
    is_official BOOLEAN,
    fetch_time TIMESTAMP
);
